### ISSUE TITLE
Cannot run the main executable

### ISSUE THREAD

**Issue by ketenburhan** [r4gus/nodus#2]
**Describe the bug**
I just cloned the repo to my local machine (Arch Linux) and I cannot run the main executable with Cargo.

**To Reproduce**
1. Run `git clone ...`
2. Run `cargo run` or `cargo run --release`
3. See error below

**Expected behavior**
Expected the window to not close.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux (Arch Linux) with X11
 - main branch

**Additional context**
output of `cargo run --release` (warnings skipped):
```
    Finished release [optimized] target(s) in 2m 41s
     Running `target/release/nodus`
2022-02-17T12:49:44.244920Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1
2022-02-17T12:49:44.302552Z  INFO bevy_render::renderer: AdapterInfo { name: "Unknown AMD GPU", vendor: 4098, device: 5708, device_type: IntegratedGpu, backend: Vulkan }
2022-02-17T12:49:44.674380Z  INFO nodus::gate: NodePlugin loaded
thread 'main' panicked at 'Failed to acquire next swap chain texture!: Timeout', /home/USERNAME/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_render-0.6.0/src/view/window.rs:161:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by r4gus** [comment]
Hi, thanks for the notice.

That is probably an AMD driver issue related to [Bevy - #3606](https://github.com/bevyengine/bevy/issues/3606).

At first glance, there are two possible solutions to the problem:

1. In `src/main.rs` turn `vsync` off, i.e. `vsync: false`.
2. You could also try to switch to `RADV` if you're currently using `AMDVLK` (maybe [this](https://wiki.archlinux.org/title/Vulkan#Selecting_Vulkan_driver) can help).

**Comment by r4gus** [comment]
This issue is probably related to Bevy so there isn't much I can do about it.

**Comment by ketenburhan** [comment]
> Hi, thanks for the notice.
> 
> That is probably an AMD driver issue related to [Bevy - #3606](https://github.com/bevyengine/bevy/issues/3606).
> 
> At first glance, there are two possible solutions to the problem:
> 
> 1. In `src/main.rs` turn `vsync` off, i.e. `vsync: false`.
> 2. You could also try to switch to `RADV` if you're currently using `AMDVLK` (maybe [this](https://wiki.archlinux.org/title/Vulkan#Selecting_Vulkan_driver) can help).

Running with `AMD_VULKAN_ICD=RADV cargo run` helped.

**Comment by r4gus** [comment]
Thanks for the reply
