### ISSUE TITLE
failed to run custom build command for `wayland-sys v0.29.4` on linux mint

### ISSUE THREAD

**Issue by pyweeker** [r4gus/nodus#3]
Hello, i can not compile , i have intel microprocesseur with nvidia graphic card on linux mint.

i also tried this : 
 **sudo apt install libxcb-shape0-dev libxcb-xfixes0-dev**
i have already most recent packets.

here is the error message:
...
Compiling lewton v0.10.2
error: failed to run custom build command for `wayland-sys v0.29.4`

Caused by:
  process didn't exit successfully: `/media/USERNAME/mydisk/myfolder/nodus-main/target/debug/build/wayland-sys-8c33ab3da59f0eaf/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=WAYLAND_CLIENT_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=WAYLAND_CLIENT_STATIC
  cargo:rerun-if-env-changed=WAYLAND_CLIENT_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: `"pkg-config" "--libs" "--cflags" "wayland-client"` did not exit successfully: exit status: 1
  error: could not find system library 'wayland-client' required by the 'wayland-sys' crate

  --- stderr
  Package wayland-client was not found in the pkg-config search path.
  Perhaps you should add the directory containing `wayland-client.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'wayland-client' found
  ', /home/USERNAME/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-sys-0.29.4/build.rs:10:47
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

=============== > FIX
in [dependencies]  just add this line:
winit = "0.26.1"

**Comment by r4gus** [comment]
Thanks for the notice.

That's odd, did you install all dependencies as mentioned [here](https://github.com/bevyengine/bevy/blob/main/docs/linux_dependencies.md)?
___

from `linux_dependencies.md`:

```bash
sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev
```

if using Wayland, you will also need to install

```bash
sudo apt-get install libwayland-dev libxkbcommon-dev
```
___

**Comment by r4gus** [comment]
No reply for a month.

```
could not find system library 'wayland-client' required by the 'wayland-sys' crate
```
looks like a missing dependency. Should be fixable by installing all required dependencies as mentioned [above](https://github.com/r4gus/nodus/issues/3#issuecomment-1047731571).
